dist: bionic
language: minimal

env:
  matrix:
    - MONGODB=3.6.23
    - MONGODB=4.0.23
    - MONGODB=4.2.13
    - MONGODB=4.4.5

install:
  - curl -fsSL https://crystal-lang.org/install.sh | sudo bash
  - wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-ubuntu1804-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-ubuntu1804-${MONGODB}/bin/mongod --version

before_script:
  - shards install
  - mkdir ${PWD}/mongodb-linux-x86_64-ubuntu1804-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-ubuntu1804-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-ubuntu1804-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-ubuntu1804-${MONGODB}/mongodb.log --fork

script:
  - crystal spec